# Generated by Django 2.1.1 on 2019-02-21 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('article', models.ManyToManyField(blank=True, to='groups.Article', verbose_name='Articles')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolRight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Level', models.CharField(choices=[('Prof', 'Prof'), ('Student', 'Student')], default='Student', max_length=20)),
                ('ERPUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.ERPUser')),
                ('School', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.School')),
            ],
        ),
        migrations.AlterField(
            model_name='membergroup',
            name='members',
            field=models.ManyToManyField(related_name='members_group', to='groups.ERPUser'),
        ),
        migrations.AddField(
            model_name='school',
            name='group',
            field=models.ManyToManyField(blank=True, to='groups.MemberGroup', verbose_name='Groupes'),
        ),
        migrations.AddField(
            model_name='school',
            name='media',
            field=models.ManyToManyField(blank=True, to='groups.Media', verbose_name='Médias'),
        ),
    ]
