# Generated by Django 2.1.1 on 2018-09-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('video', models.CharField(max_length=30)),
                ('image', models.CharField(max_length=30)),
                ('text', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='media',
            field=models.ManyToManyField(to='groups.Media'),
        ),
        migrations.AddField(
            model_name='membergroup',
            name='articles',
            field=models.ManyToManyField(to='groups.Article'),
        ),
    ]
