# Generated by Django 2.1.1 on 2019-02-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio'),
        ),
        migrations.AddField(
            model_name='media',
            name='guitarpro',
            field=models.FileField(blank=True, null=True, upload_to='gp'),
        ),
        migrations.AddField(
            model_name='media',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdf'),
        ),
        migrations.AddField(
            model_name='media',
            name='youtubeurl',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='text',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
