# Generated by Django 2.1.1 on 2018-11-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_auto_20181118_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='image',
            field=models.FileField(null=True, upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='media',
            name='video',
            field=models.FileField(null=True, upload_to='static/videos'),
        ),
    ]
