# Generated by Django 2.1.1 on 2019-02-27 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_auto_20190222_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolright',
            old_name='ERPUser',
            new_name='erp_user',
        ),
        migrations.RenameField(
            model_name='schoolright',
            old_name='Level',
            new_name='level',
        ),
        migrations.RenameField(
            model_name='schoolright',
            old_name='School',
            new_name='school',
        ),
    ]
