# Generated by Django 2.1.1 on 2019-03-03 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_lessondate_lessons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessons',
            name='dates',
        ),
        migrations.AddField(
            model_name='lessondate',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='groups.Lessons'),
        ),
    ]
